name: Upload pipeline

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    upload:
        runs-on: ubuntu-latest

        steps:
            - name: Install packages
              run: pip3 install -r ./requirements.txt
            - name: Connect to Kubeflow
              run: kfp --endpoint ${{ secrets.KUBEFLOW_ENDPOINT }}
            - name: KubeFlow Diagnose
              run: kfp diagnose_me
            - name: Upload pipeline to KubeFlow
              run: kfp pipeline upload
            # - name: Upload pipeline to Kubeflow
            #   run: python3 ./pipeline/pipeline.py
